server:
  servlet:
    context-path: /seckill
  port: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
  httpclient:
    connection-timeout: 1000
