renren:
    redis:
        open: false
    shiro:
        redis: false
management:
    endpoints:
        web:
            exposure:
                include: '*'
feign:
    sentinel:
        enabled: true
